-- Create the public products table used by the site.
-- If you already have a table with the exact columns, you can skip the CREATE TABLE block
-- and only run the RLS / policy statements.

create table if not exists public.products (
  product_id bigint generated by default as identity primary key,
  korean_name text not null,
  english_name text not null,
  product_type text,
  meat_type text
);

alter table public.products enable row level security;

drop policy if exists "public read products" on public.products;

create policy "public read products"
on public.products
for select
using (true);

-- Optional: allow the app to react to changes through Supabase realtime.
-- In the Supabase dashboard, enable Realtime for this table if you want live updates.